name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/rifsxd/android_t_kernel_realme_RMX3511
          kernel-dir: realme_RMX3511
          kernel-branch: dev
          config: RMX3511_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: false
          ksu-version: v0.9.5
          android-version: 12
          aosp-clang-version: r416183b
          disable-lto: false
          anykernel3: true

    - name: Zip Kernel Boot Files
      run: |
        zip -r kernel_boot_files.zip out/arch/arm64/boot/

    - name: Upload Kernel Boot Files
      uses: actions/upload-artifact@v3
      with:
        name: kernel-boot-files
        path: kernel_boot_files.zip
