name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/realme-kernel-opensource/realme_C31_C33_C35_narzo50A-Prime-AndroidT-kernel-source
          kernel-dir: realme_C35
          kernel-branch: master
          config: sprd_qogirl6_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 13
          aosp-clang-version: r450784d
          python-27: true
          disable-lto: true
          anykernel3: true
